using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Funeral.Model
{
   public class ApplicationSettingsModel
    {
       public ApplicationSettingsModel()
        {
            
            ApplicationName = string.Empty;
            ApplicationLogoPath = string.Empty;
            OwnerFirstName = string.Empty;
            OwnerSurname = string.Empty;
            OwnerTelNumber = string.Empty;
            OwnerCellNumber = string.Empty;
            ManagerFirstName = string.Empty;
            ManageSurname = string.Empty;
            ManageTelNumber = string.Empty;
            ManageCellNumber = string.Empty;
            BusinessAddressLine1 = string.Empty;
            BusinessAddressLine2 = string.Empty;
            BusinessAddressLine3 = string.Empty;
            BusinessAddressLine4 = string.Empty;
            BusinessPostalCode = string.Empty;
            FSBNumber = string.Empty;
            CereliaAPIKey = string.Empty;
            RegistrationNumber = string.Empty;
            ManageSlogan = string.Empty;
            ManageEmail = string.Empty;
            ManageFaxNumber = string.Empty;
            OwnerEmail = string.Empty;
            VatNo = string.Empty;
            //IsAutoGeneratedPolicyNo = true; 

        }
       public int pkiApplicationID { get; set; }
       public string ApplicationName { get; set; }
       public string ApplicationLogoPath { get; set; }
       public string OwnerFirstName { get; set; }
       public string OwnerSurname { get; set; }
       public string OwnerTelNumber { get; set; }
       public string OwnerCellNumber { get; set; }
       public string ManagerFirstName { get; set; }
       public string ManageSurname { get; set; }
       public string ManageTelNumber { get; set; }
       public string ManageCellNumber { get; set; }
       public string BusinessAddressLine1 { get; set; }
       public string BusinessAddressLine2 { get; set; }
       public string BusinessAddressLine3 { get; set; }
       public string BusinessAddressLine4 { get; set; }
       public string BusinessPostalCode { get; set; }
       public string FSBNumber { get; set; }
       public string CereliaAPIKey { get; set; }
       public string RegistrationNumber { get; set; }
       public string ManageSlogan { get; set; }
       public string ManageEmail { get; set; }
       public string ManageFaxNumber { get; set; }
       public string OwnerEmail { get; set; }
       public Guid parlourid { get; set; }
       public Byte[] ApplicationLogo { get; set; }
       public string ApplicationRules { get; set; }
       public Boolean IsAutoGeneratedPolicyNo { get; set; }
       public string VatNo { get; set; }
       public Guid Currentparlourid { get; set; }
    }
}
