using Funeral.Model;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Funeral.DAL
{
    public class ToolsSetingDAL
    {
        public static int UploadApplicationLogo(ApplicationSettingsModel model)
        {
            DbParameter[] ObjParam = new DbParameter[3];
            ObjParam[0] = new DbParameter("@ApplicationLogoPath", DbParameter.DbType.VarChar, 0, model.ApplicationLogoPath);
            ObjParam[1] = new DbParameter("@ApplicationLogo", DbParameter.DbType.Image, 0, model.ApplicationLogo);
            ObjParam[2] = new DbParameter("@pkiApplicationID", DbParameter.DbType.Int, 0, model.pkiApplicationID);
            //return 1;
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, "UploadApplicationLogo", ObjParam));
        }
        public static SqlDataReader SaveApplication(ApplicationSettingsModel model)
        {
            AdditionalMemberInfoModel model1 = new AdditionalMemberInfoModel();
            string query = "SaveApplicationSetting";
            DbParameter[] ObjParam = new DbParameter[28];
            ObjParam[0] = new DbParameter("@pkiApplicationID", DbParameter.DbType.Int, 0, model.pkiApplicationID);
            ObjParam[1] = new DbParameter("@ApplicationName", DbParameter.DbType.NVarChar, 0, model.ApplicationName);
            ObjParam[2] = new DbParameter("@ApplicationLogoPath", DbParameter.DbType.NVarChar, 0, model.ApplicationLogoPath);
            ObjParam[3] = new DbParameter("@OwnerFirstName", DbParameter.DbType.NVarChar, 0, model.OwnerFirstName);
            ObjParam[4] = new DbParameter("@OwnerSurname", DbParameter.DbType.NVarChar, 0, model.OwnerSurname);
            ObjParam[5] = new DbParameter("@OwnerTelNumber", DbParameter.DbType.NVarChar, 0, model.OwnerTelNumber);
            ObjParam[6] = new DbParameter("@OwnerCellNumber", DbParameter.DbType.NVarChar, 0, model.OwnerCellNumber);
            ObjParam[7] = new DbParameter("@ManagerFirstName", DbParameter.DbType.NVarChar, 0, model.ManagerFirstName);
            ObjParam[8] = new DbParameter("@ManageSurname", DbParameter.DbType.NVarChar, 0, model.ManageSurname);
            ObjParam[9] = new DbParameter("@ManageTelNumber", DbParameter.DbType.NVarChar, 0, model.ManageTelNumber);
            ObjParam[10] = new DbParameter("@ManageCellNumber", DbParameter.DbType.NVarChar, 0, model.ManageCellNumber);
            ObjParam[11] = new DbParameter("@BusinessAddressLine1", DbParameter.DbType.NVarChar, 0, model.BusinessAddressLine1);
            ObjParam[12] = new DbParameter("@BusinessAddressLine2", DbParameter.DbType.NVarChar, 0, model.BusinessAddressLine2);
            ObjParam[13] = new DbParameter("@BusinessAddressLine3", DbParameter.DbType.NVarChar, 0, model.BusinessAddressLine3);
            ObjParam[14] = new DbParameter("@BusinessAddressLine4", DbParameter.DbType.NVarChar, 0, model.BusinessAddressLine4);
            ObjParam[15] = new DbParameter("@BusinessPostalCode", DbParameter.DbType.NVarChar, 0, model.BusinessPostalCode);
            ObjParam[16] = new DbParameter("@FSBNumber", DbParameter.DbType.NVarChar, 0, model.FSBNumber);
            ObjParam[17] = new DbParameter("@parlourid", DbParameter.DbType.UniqueIdentifier, 0, model.parlourid);
            ObjParam[18] = new DbParameter("@CereliaAPIKey", DbParameter.DbType.NVarChar, 0, model.CereliaAPIKey);
            ObjParam[19] = new DbParameter("@RegistrationNumber", DbParameter.DbType.NVarChar, 0, model.RegistrationNumber);
            ObjParam[20] = new DbParameter("@ManageSlogan", DbParameter.DbType.NVarChar, 0, model.ManageSlogan);
            ObjParam[21] = new DbParameter("@ManageEmail", DbParameter.DbType.NVarChar, 0, model.ManageEmail);
            ObjParam[22] = new DbParameter("@ManageFaxNumber", DbParameter.DbType.NVarChar, 0, model.ManageFaxNumber);
            ObjParam[23] = new DbParameter("@OwnerEmail", DbParameter.DbType.NVarChar, 0, model.OwnerEmail);
            ObjParam[24] = new DbParameter("@ApplicationRules", DbParameter.DbType.NVarChar, 0, model.ApplicationRules);
            ObjParam[25] = new DbParameter("@VatNo", DbParameter.DbType.NVarChar, 0, model.VatNo);
            ObjParam[26] = new DbParameter("@IsAutoGeneratedPolicyNo", DbParameter.DbType.Bit, 0, model.IsAutoGeneratedPolicyNo);
            ObjParam[27] = new DbParameter("@Currentparlourid", DbParameter.DbType.UniqueIdentifier, 0, model.Currentparlourid);
           
            return DbConnection.GetDataReader(CommandType.StoredProcedure, query, ObjParam);

        }
        public static SqlDataReader SaveAdditionalApplication(AdditionalApplicationSettingsModel model)
        {           
            string query = "AddUpdateAdditionalApplicationSettings";
            DbParameter[] ObjParam = new DbParameter[11];
            ObjParam[0] = new DbParameter("@pkiParlourid", DbParameter.DbType.UniqueIdentifier, 0, model.pkiParlourid);
            ObjParam[1] = new DbParameter("@spUPuser", DbParameter.DbType.NVarChar, 0, model.spUPuser);
            ObjParam[2] = new DbParameter("@spUPpass", DbParameter.DbType.NVarChar, 0, model.spUPpass);
            ObjParam[3] = new DbParameter("@spUPpinpad", DbParameter.DbType.NVarChar, 0, model.spUPpinpad);
            ObjParam[4] = new DbParameter("@spValuser", DbParameter.DbType.NVarChar, 0, model.spValuser);
            ObjParam[5] = new DbParameter("@spValpass", DbParameter.DbType.NVarChar, 0, model.spValpass);
            ObjParam[6] = new DbParameter("@spValpinpad", DbParameter.DbType.NVarChar, 0, model.spValpinpad);
            ObjParam[7] = new DbParameter("@spCCuser", DbParameter.DbType.NVarChar, 0, model.spCCuser);
            ObjParam[8] = new DbParameter("@spCCpass", DbParameter.DbType.NVarChar, 0, model.spCCpass);
            ObjParam[9] = new DbParameter("@spCCpinpad", DbParameter.DbType.NVarChar, 0, model.spCCpinpad);
            ObjParam[10] = new DbParameter("@GenerateMember", DbParameter.DbType.NVarChar, 0, model.GenerateMember);            
            return DbConnection.GetDataReader(CommandType.StoredProcedure, query, ObjParam);

        }
        public static SqlDataReader SaveAgentInfo(AgentInfoSetupModel model)
        {
            AdditionalMemberInfoModel model1 = new AdditionalMemberInfoModel();
            DbParameter[] ObjParam = new DbParameter[14];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, model.ID);
            ObjParam[1] = new DbParameter("@surname", DbParameter.DbType.NVarChar, 0, model.Surname);
            ObjParam[2] = new DbParameter("@fullname", DbParameter.DbType.NVarChar, 0, model.Fullname);
            ObjParam[3] = new DbParameter("@percentage", DbParameter.DbType.Decimal, 0, model.percentage);
            ObjParam[4] = new DbParameter("@contactnumber", DbParameter.DbType.NVarChar, 0, model.ContactNumber);
            ObjParam[5] = new DbParameter("@code", DbParameter.DbType.NVarChar, 0, model.Code);
            ObjParam[6] = new DbParameter("@email", DbParameter.DbType.NVarChar, 0, model.Email);
            ObjParam[7] = new DbParameter("@address1", DbParameter.DbType.NVarChar, 0, model.Address1);
            ObjParam[8] = new DbParameter("@address2", DbParameter.DbType.NVarChar, 0, model.Address2);
            ObjParam[9] = new DbParameter("@address3", DbParameter.DbType.NVarChar, 0, model.Address3);
            ObjParam[10] = new DbParameter("@address4", DbParameter.DbType.NVarChar, 0, model.Address4);
            ObjParam[11] = new DbParameter("@LastModified", DbParameter.DbType.DateTime, 0, model.LastModified);
            ObjParam[12] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, model.ModifiedUser);
            ObjParam[13] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, model.parlourid);

            return DbConnection.GetDataReader(CommandType.StoredProcedure, "SaveAgentInfo", ObjParam);
        }
        public static SqlDataReader SaveBankingDetail(BankingDetailSending Model)
        {
            AdditionalMemberInfoModel model1 = new AdditionalMemberInfoModel();
            DbParameter[] ObjParam = new DbParameter[9];
            ObjParam[0] = new DbParameter("@AccountHolder", DbParameter.DbType.NVarChar, 0, Model.AccountHolder);
            ObjParam[1] = new DbParameter("@Bankname", DbParameter.DbType.NVarChar, 0, Model.Bankname);
            ObjParam[2] = new DbParameter("@AccountNumber", DbParameter.DbType.NVarChar, 0, Model.AccountNumber);
            ObjParam[3] = new DbParameter("@Accounttype", DbParameter.DbType.NVarChar, 0, Model.Accounttype);
            ObjParam[4] = new DbParameter("@Branch", DbParameter.DbType.NVarChar, 0, Model.Branch);
            ObjParam[5] = new DbParameter("@Branchcode", DbParameter.DbType.NVarChar, 0, Model.Branchcode);
            ObjParam[6] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, Model.parlourid);
            ObjParam[7] = new DbParameter("@LastModified", DbParameter.DbType.DateTime, 0, Model.LastModified);
            ObjParam[8] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, Model.ModifiedUser);


            return DbConnection.GetDataReader(CommandType.StoredProcedure, "SaveBankingDetail", ObjParam);
        }


        public static SqlDataReader GetUserAccessByID(int ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetUserAccessByID", ObjParam);
        }
        public static SqlDataReader GetApplictionByParlourID(Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "ApplicationSelectByParlourId", ObjParam);
        }
        public static SqlDataReader GetApplictionByID(int ID)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "ApplicationSelectById", ObjParam);
        }


        public static SqlDataReader GetBankingByID(Guid ID)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.UniqueIdentifier, 0, ID);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "BankingSelectById", ObjParam);
        }

        public static SqlDataReader GetAgentByID(int ID)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "AgentSelectById", ObjParam);
        }
        public static SqlDataReader GetAllCompanys(Guid ParlourId, int PageSize, int PageNum, string Keyword, string SortBy, string SortOrder)
        {
            DbParameter[] ObjParam = new DbParameter[6];
           
            ObjParam[0] = new DbParameter("@pagesize", DbParameter.DbType.Int, 0, PageSize);
            ObjParam[1] = new DbParameter("@pagenum", DbParameter.DbType.Int, 0, PageNum);
            ObjParam[2] = new DbParameter("@Keyword", DbParameter.DbType.NVarChar, 0, Keyword);
            ObjParam[3] = new DbParameter("@field", DbParameter.DbType.NVarChar, 0, SortBy);
            ObjParam[4] = new DbParameter("@orderby", DbParameter.DbType.NVarChar, 0, SortOrder);
            ObjParam[5] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetAllCompanys", ObjParam);
        }
        public static SqlDataReader GetAllAgentInfo(Guid ParlourId, int PageSize, int PageNum, string Keyword, string SortBy, string SortOrder)
        {
            DbParameter[] ObjParam = new DbParameter[6];

            ObjParam[0] = new DbParameter("@pagesize", DbParameter.DbType.Int, 0, PageSize);
            ObjParam[1] = new DbParameter("@pagenum", DbParameter.DbType.Int, 0, PageNum);
            ObjParam[2] = new DbParameter("@Keyword", DbParameter.DbType.NVarChar, 0, Keyword);
            ObjParam[3] = new DbParameter("@field", DbParameter.DbType.NVarChar, 0, SortBy);
            ObjParam[4] = new DbParameter("@orderby", DbParameter.DbType.NVarChar, 0, SortOrder);
            ObjParam[5] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetAllAgentInfo", ObjParam);
        }
      
        public static int DeleteCompany(int id)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@pkiApplicationID", DbParameter.DbType.Int, 0, id);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, "DeleteCompany", ObjParam));
        }
        public static int DeleteAgent(int id)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, id);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, "DeleteAgent", ObjParam));
        }
        public static SqlDataReader EditsmsGroupbyID(int ID)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "EditsmsGroupbyID", ObjParam);
        }
        public static SqlDataReader GetsmsGroupbyID(int ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetsmsGroupbyID", ObjParam);
        }
        public static int SaveSmsGroupDetails(smsSendingGroupModel model)
        {
            AdditionalMemberInfoModel model1 = new AdditionalMemberInfoModel();
            string query = "SaveSmsGroupDetails";
            DbParameter[] ObjParam = new DbParameter[6];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, model.ID);
            ObjParam[1] = new DbParameter("@fkiCompanyID", DbParameter.DbType.Int, 0, model.fkiCompanyID);
            ObjParam[2] = new DbParameter("@fkismstempletID", DbParameter.DbType.NVarChar, 0, model.fkismstempletID);
            ObjParam[3] = new DbParameter("@smstempletName", DbParameter.DbType.NVarChar, 0, model.smstempletName);
            ObjParam[4] = new DbParameter("@LastModified", DbParameter.DbType.NVarChar, 0, model.LastModified);
            ObjParam[5] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, model.ModifiedUser);

            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, query, ObjParam));

        }
        public static SqlDataReader GetSecureGrouList()
        {
            DbParameter[] ObjParam = new DbParameter[0];
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetSecureGrouList", ObjParam);
        }
        public static SqlDataReader GetUserByID(string ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.NVarChar, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetUserByID", ObjParam);
        }
        public static int SaveUserDetails(SecureUsersModel model)
        {
            AdditionalMemberInfoModel model1 = new AdditionalMemberInfoModel();
            string query = "SaveSecureUserDetails";
            DbParameter[] ObjParam = new DbParameter[22];
            ObjParam[0] = new DbParameter("@PkiUserID", DbParameter.DbType.Int, 0, model.PkiUserID);
            ObjParam[1] = new DbParameter("@UserName", DbParameter.DbType.NVarChar, 0, model.UserName);
            ObjParam[2] = new DbParameter("@Password", DbParameter.DbType.NVarChar, 0, model.Password);
            ObjParam[3] = new DbParameter("@EmployeeSurname", DbParameter.DbType.NVarChar, 0, model.EmployeeSurname);
            ObjParam[4] = new DbParameter("@EmployeeFullname", DbParameter.DbType.NVarChar, 0, model.EmployeeFullname);
            ObjParam[5] = new DbParameter("@EmployeeIDNumber", DbParameter.DbType.NVarChar, 0, model.EmployeeIDNumber);
            ObjParam[6] = new DbParameter("@EmployeeContactNumber", DbParameter.DbType.NVarChar, 0, model.EmployeeContactNumber);
            ObjParam[7] = new DbParameter("@EmployeeAddress1", DbParameter.DbType.NVarChar, 0, model.EmployeeAddress1);
            ObjParam[8] = new DbParameter("@EmployeeAddress2", DbParameter.DbType.NVarChar, 0, model.EmployeeAddress2);
            ObjParam[9] = new DbParameter("@EmployeeAddress3", DbParameter.DbType.NVarChar, 0, model.EmployeeAddress3);
            ObjParam[10] = new DbParameter("@EmployeeAddress4", DbParameter.DbType.NVarChar, 0, model.EmployeeAddress4);
            ObjParam[11] = new DbParameter("@LastModified", DbParameter.DbType.DateTime, 0, model.LastModified);
            ObjParam[12] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, model.ModifiedUser);
            ObjParam[13] = new DbParameter("@Email", DbParameter.DbType.NVarChar, 0, model.Email);
            ObjParam[14] = new DbParameter("@parlourid", DbParameter.DbType.UniqueIdentifier, 0, model.parlourid);
            ObjParam[15] = new DbParameter("@Code", DbParameter.DbType.NVarChar, 0, model.Code);
            ObjParam[16] = new DbParameter("@AgentName", DbParameter.DbType.NVarChar, 0, model.AgentName);
            ObjParam[17] = new DbParameter("@AgentSurname", DbParameter.DbType.NVarChar, 0, model.AgentSurname);

            ObjParam[18] = new DbParameter("@BranchId", DbParameter.DbType.UniqueIdentifier, 0, model.BranchId);
            ObjParam[19] = new DbParameter("@CustomId1", DbParameter.DbType.NVarChar, 0, model.CustomId1);
            ObjParam[20] = new DbParameter("@CustomId2", DbParameter.DbType.NVarChar, 0, model.CustomId2);
            ObjParam[21] = new DbParameter("@CustomId3", DbParameter.DbType.NVarChar, 0, model.CustomId3);

            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, query, ObjParam));

        }
        public static int SaveUserGroupDetails(SecureUserGroupsModel model)
        {
            AdditionalMemberInfoModel model1 = new AdditionalMemberInfoModel();
            string query = "SaveSecureUserGroupDetails";
            DbParameter[] ObjParam = new DbParameter[6];
            ObjParam[0] = new DbParameter("@pkiSecureUserGroups", DbParameter.DbType.Int, 0, model.pkiSecureUserGroups);
            ObjParam[1] = new DbParameter("@fkiSecureUserID", DbParameter.DbType.Int, 0, model.fkiSecureUserID);
            ObjParam[2] = new DbParameter("@fkiSecureGroupID", DbParameter.DbType.NVarChar, 0, model.fkiSecureGroupID);
            ObjParam[3] = new DbParameter("@sSecureUserGroupDesc", DbParameter.DbType.NVarChar, 0, model.sSecureUserGroupDesc);
            ObjParam[4] = new DbParameter("@LastModified", DbParameter.DbType.DateTime, 0, model.LastModified);
            ObjParam[5] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, model.ModifiedUser);

            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, query, ObjParam));

        }
        public static SqlDataReader GetAllUsers(Guid ParlourId, int PageSize, int PageNum, string Keyword, string SortBy, string SortOrder)
        {
            DbParameter[] ObjParam = new DbParameter[6];

            ObjParam[0] = new DbParameter("@pagesize", DbParameter.DbType.Int, 0, PageSize);
            ObjParam[1] = new DbParameter("@pagenum", DbParameter.DbType.Int, 0, PageNum);
            ObjParam[2] = new DbParameter("@Keyword", DbParameter.DbType.NVarChar, 0, Keyword);
            ObjParam[3] = new DbParameter("@field", DbParameter.DbType.NVarChar, 0, SortBy);
            ObjParam[4] = new DbParameter("@orderby", DbParameter.DbType.NVarChar, 0, SortOrder);
            ObjParam[5] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "UserSelectAllByPage", ObjParam);
        }
        public static int DeleteUser(int id)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@PkiUserID", DbParameter.DbType.Int, 0, id);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, "DeleteUsers", ObjParam));
        }
        public static SqlDataReader EditUserbyID(int ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "UserSelectbyID", ObjParam);
        }
        public static SqlDataReader EditSecurUserbyID(int ID)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "ScureUserSelectbyID", ObjParam);
        }
        public static SqlDataReader GetBranchByID(string ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.NVarChar, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetBranchByID", ObjParam);
        }
        public static Guid SaveBranchDetails(BranchModel model)
        {
            AdditionalMemberInfoModel model1 = new AdditionalMemberInfoModel();
            string query = "SaveBranchDetails";
            DbParameter[] ObjParam = new DbParameter[14];
            ObjParam[0] = new DbParameter("@Brancheid", DbParameter.DbType.UniqueIdentifier, 0, model.Brancheid);
            ObjParam[1] = new DbParameter("@BranchName", DbParameter.DbType.NVarChar, 0, model.BranchName);
            ObjParam[2] = new DbParameter("@Parlourid", DbParameter.DbType.UniqueIdentifier, 0, model.Parlourid);
            ObjParam[3] = new DbParameter("@LastModified", DbParameter.DbType.DateTime, 0, model.LastModified);
            ObjParam[4] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, model.ModifiedUser);
            ObjParam[5] = new DbParameter("@Address1", DbParameter.DbType.NVarChar, 0, model.Address1);
            ObjParam[6] = new DbParameter("@Address2", DbParameter.DbType.NVarChar, 0, model.Address2);
            ObjParam[7] = new DbParameter("@Address3", DbParameter.DbType.NVarChar, 0, model.Address3);
            ObjParam[8] = new DbParameter("@Address4", DbParameter.DbType.NVarChar, 0, model.Address4);
            ObjParam[9] = new DbParameter("@Code", DbParameter.DbType.NVarChar, 0, model.Code);
            ObjParam[10] = new DbParameter("@TelNumber", DbParameter.DbType.NVarChar, 0, model.TelNumber);
            ObjParam[11] = new DbParameter("@CellNumber", DbParameter.DbType.NVarChar, 0, model.CellNumber);
            ObjParam[12] = new DbParameter("@BranchCode", DbParameter.DbType.NVarChar, 0, model.BranchCode);
            ObjParam[13] = new DbParameter("@Region", DbParameter.DbType.NVarChar, 0, model.Region);

            return new Guid(DbConnection.GetScalarValue(CommandType.StoredProcedure, query, ObjParam).ToString());

        }
        public static SqlDataReader GetAllBranches(Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[1];

            ObjParam[0] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetAllBranches", ObjParam);
        }
        public static SqlDataReader EditBranchbyID(Guid ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.UniqueIdentifier, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "EditBranchbyID", ObjParam);
        }
        public static int DeleteBranch(Guid id)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@BranchID", DbParameter.DbType.UniqueIdentifier, 0, id);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, "DeleteBranch", ObjParam));
        }

        public static int DeleteBank(Int32 id)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@BankId", DbParameter.DbType.Int, 0, id);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, "DeleteBank", ObjParam));
        }
        public static SqlDataReader GetAllSocietyes(Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[1];

            ObjParam[0] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetAllSocietyes", ObjParam);
        }
        public static SqlDataReader GetAllSocietye(Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[1];

            ObjParam[0] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "getAllSociety", ObjParam);
        }
        public static SqlDataReader EditSocietybyID(int ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "EditSocietybyID", ObjParam);
        }
        public static SqlDataReader GetSocietyByID(string ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.NVarChar, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetSocietyByID", ObjParam);
        }
        public static int SaveSocietyDetails(SocietyModel model)
        {
            AdditionalMemberInfoModel model1 = new AdditionalMemberInfoModel();
            string query = "SaveSocietyDetails";
            DbParameter[] ObjParam = new DbParameter[5];
            ObjParam[0] = new DbParameter("@pkiSocietyID", DbParameter.DbType.Int, 0, model.pkiSocietyID);
            ObjParam[1] = new DbParameter("@SocietyName", DbParameter.DbType.NVarChar, 0, model.SocietyName);
            ObjParam[2] = new DbParameter("@parlourid", DbParameter.DbType.UniqueIdentifier, 0, model.parlourid);
            ObjParam[3] = new DbParameter("@LastModified", DbParameter.DbType.DateTime, 0, model.LastModified);
            ObjParam[4] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, model.ModifiedUser);

            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, query, ObjParam));

        }
        public static int DeleteSociety(int id)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@pkiSocietyID", DbParameter.DbType.Int, 0, id);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, "DeleteSociety", ObjParam));
        }
        public static SqlDataReader GetAllVendores(Guid ParlourId, int PageSize, int PageNum, string Keyword, string SortBy, string SortOrder)
        {
            DbParameter[] ObjParam = new DbParameter[6];

            ObjParam[0] = new DbParameter("@pagesize", DbParameter.DbType.Int, 0, PageSize);
            ObjParam[1] = new DbParameter("@pagenum", DbParameter.DbType.Int, 0, PageNum);
            ObjParam[2] = new DbParameter("@Keyword", DbParameter.DbType.NVarChar, 0, Keyword);
            ObjParam[3] = new DbParameter("@field", DbParameter.DbType.NVarChar, 0, SortBy);
            ObjParam[4] = new DbParameter("@orderby", DbParameter.DbType.NVarChar, 0, SortOrder);
            ObjParam[5] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetAllVendores", ObjParam);
        }
        public static SqlDataReader EditVendorbyID(int ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "EditVendorbyID", ObjParam);
        }
        public static SqlDataReader GetVendorByID(string ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.NVarChar, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetVendorByID", ObjParam);
        }
        public static int SaveVendorDetails(VendorModel model)
        {
            AdditionalMemberInfoModel model1 = new AdditionalMemberInfoModel();
            string query = "SaveVendorDetails";
            DbParameter[] ObjParam = new DbParameter[5];
            ObjParam[0] = new DbParameter("@pkiVendorID", DbParameter.DbType.Int, 0, model.pkiVendorID);
            ObjParam[1] = new DbParameter("@VendorName", DbParameter.DbType.NVarChar, 0, model.VendorName);
            ObjParam[2] = new DbParameter("@parlourid", DbParameter.DbType.UniqueIdentifier, 0, model.parlourid);
            ObjParam[3] = new DbParameter("@LastModified", DbParameter.DbType.DateTime, 0, model.LastModified);
            ObjParam[4] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, model.ModifiedUser);

            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, query, ObjParam));

        }
        public static int DeleteVendor(int id)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@pkiVendorID", DbParameter.DbType.Int, 0, id);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, "DeleteVendor", ObjParam));
        }
        public static SqlDataReader GetAllExpenseses(Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[1];

            ObjParam[0] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetAllExpenseses", ObjParam);
        }
        public static SqlDataReader EditExpensesbyID(int ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "EditExpensesbyID", ObjParam);
        }
        public static SqlDataReader GetExpensesByID(string ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.NVarChar, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetExpensesByID", ObjParam);
        }
        public static int SaveExpensesDetails(ExpensesModel model)
        {
            AdditionalMemberInfoModel model1 = new AdditionalMemberInfoModel();
            string query = "SaveExpensesDetails";
            DbParameter[] ObjParam = new DbParameter[5];
            ObjParam[0] = new DbParameter("@pkiExpenseCategoryID", DbParameter.DbType.Int, 0, model.pkiExpenseCategoryID);
            ObjParam[1] = new DbParameter("@Category", DbParameter.DbType.NVarChar, 0, model.Category);
            ObjParam[2] = new DbParameter("@parlourid", DbParameter.DbType.UniqueIdentifier, 0, model.parlourid);
            ObjParam[3] = new DbParameter("@LastModified", DbParameter.DbType.DateTime, 0, model.LastModified);
            ObjParam[4] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, model.ModifiedUser);

            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, query, ObjParam));

        }
        public static int DeleteExpenses(int id)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@pkiExpenseCategoryID", DbParameter.DbType.Int, 0, id);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, "DeleteExpenses", ObjParam));
        }

        public static SqlDataReader GetAddonProductByID(string ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.NVarChar, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetAddonProductByID", ObjParam);
        }

        public static Guid SaveAddonProductDetails(AddonProductsModal model)
        {
            AdditionalMemberInfoModel model1 = new AdditionalMemberInfoModel();
            string query = "SaveAddonProductDetails";
            DbParameter[] ObjParam = new DbParameter[12];
            ObjParam[0] = new DbParameter("@pkiProductID", DbParameter.DbType.UniqueIdentifier, 0, model.pkiProductID);
            ObjParam[1] = new DbParameter("@ProductName", DbParameter.DbType.NVarChar, 0, model.ProductName);
            ObjParam[2] = new DbParameter("@Parlourid", DbParameter.DbType.UniqueIdentifier, 0, model.Parlourid);
            ObjParam[3] = new DbParameter("@LastModified", DbParameter.DbType.DateTime, 0, model.LastModified);
            ObjParam[4] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, model.ModifiedUser);
            ObjParam[5] = new DbParameter("@DateCreated", DbParameter.DbType.DateTime, 0, model.DateCreated);
            ObjParam[6] = new DbParameter("@ProductDesc", DbParameter.DbType.NVarChar, 0, model.ProductDesc);
            ObjParam[7] = new DbParameter("@ProductCost", DbParameter.DbType.Decimal, 0, model.ProductCost);
            ObjParam[8] = new DbParameter("@ProductCover", DbParameter.DbType.Decimal, 0, model.ProductCover);
            ObjParam[9] = new DbParameter("@IsProductOngoing", DbParameter.DbType.Int, 0, model.IsProductOngoing);
            ObjParam[10] = new DbParameter("@IsProductLaybye", DbParameter.DbType.Int, 0, model.IsProductLaybye);
            ObjParam[11] = new DbParameter("@UserId", DbParameter.DbType.NVarChar, 0, model.UserID);

            return new Guid(DbConnection.GetScalarValue(CommandType.StoredProcedure, query, ObjParam).ToString());

        }
        public static SqlDataReader GetAllAddonProductes(Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[1];

            ObjParam[0] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetAllAddonProductes", ObjParam);
        }
        public static SqlDataReader EditAddonProductbyID(Guid ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.UniqueIdentifier, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "EditAddonProductbyID", ObjParam);
        }
        public static int DeleteAddonProduct(Guid id)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@pkiProductID", DbParameter.DbType.UniqueIdentifier, 0, id);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, "DeleteAddonProduct", ObjParam));
        }

        public static SqlDataReader GetAllPlans(Guid ParlourId, int PageSize, int PageNum, string Keyword, string SortBy, string SortOrder)
        {
            DbParameter[] ObjParam = new DbParameter[6];

            ObjParam[0] = new DbParameter("@pagesize", DbParameter.DbType.Int, 0, PageSize);
            ObjParam[1] = new DbParameter("@pagenum", DbParameter.DbType.Int, 0, PageNum);
            ObjParam[2] = new DbParameter("@Keyword", DbParameter.DbType.NVarChar, 0, Keyword);
            ObjParam[3] = new DbParameter("@field", DbParameter.DbType.NVarChar, 0, SortBy);
            ObjParam[4] = new DbParameter("@orderby", DbParameter.DbType.NVarChar, 0, SortOrder);
            ObjParam[5] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetAllPlans", ObjParam);
        }
        public static SqlDataReader EditPlanbyID(int ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "EditPlanbyID", ObjParam);
        }
        public static SqlDataReader GetPlanByID(string ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.NVarChar, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetPlanByID", ObjParam);
        }
        public static int SavePlanDetails(PlanModel model)
        {
            AdditionalMemberInfoModel model1 = new AdditionalMemberInfoModel();
            string query = "SavePlanDetails";
            DbParameter[] ObjParam = new DbParameter[31];
            ObjParam[0] = new DbParameter("@pkiPlanID", DbParameter.DbType.Int, 0, model.pkiPlanID);
            ObjParam[1] = new DbParameter("@PlanName", DbParameter.DbType.NVarChar, 0, model.PlanName);
            ObjParam[2] = new DbParameter("@PlanSubscription", DbParameter.DbType.Decimal, 0, model.PlanSubscription);
            ObjParam[3] = new DbParameter("@JoiningFee", DbParameter.DbType.Decimal, 0, model.JoiningFee);
            ObjParam[4] = new DbParameter("@PlanDesc", DbParameter.DbType.NVarChar, 0, model.PlanDesc);
            ObjParam[5] = new DbParameter("@PlanUnderwriter", DbParameter.DbType.NVarChar, 0, model.PlanUnderwriter);
            //ObjParam[6] = new DbParameter("@MainMember", DbParameter.DbType.Int, 0, model.MainMember);
            ObjParam[6] = new DbParameter("@Cover", DbParameter.DbType.Decimal, 0, model.Cover);
            ObjParam[7] = new DbParameter("@Spouse", DbParameter.DbType.Int, 0, model.Spouse);
            ObjParam[8] = new DbParameter("@Children", DbParameter.DbType.Int, 0, model.Children);
            ObjParam[9] = new DbParameter("@Cover0to5year", DbParameter.DbType.Decimal, 0, model.Cover0to5year);
            ObjParam[10] = new DbParameter("@Cover6to13year", DbParameter.DbType.Decimal, 0, model.Cover6to13year);
            ObjParam[11] = new DbParameter("@Cover14to21year", DbParameter.DbType.Decimal, 0, model.Cover14to21year);
            //ObjParam[12] = new DbParameter("@Cover22to40year", DbParameter.DbType.Decimal, 0, model.Cover22to40year);
            //ObjParam[13] = new DbParameter("@Cover41to59year", DbParameter.DbType.Decimal, 0, model.Cover41to59year);
            //ObjParam[14] = new DbParameter("@Cover60to65year", DbParameter.DbType.Decimal, 0, model.Cover60to65year);
            //ObjParam[15] = new DbParameter("@Cover66to75year", DbParameter.DbType.Decimal, 0, model.Cover66to75year);
            ObjParam[12] = new DbParameter("@Adults", DbParameter.DbType.Int, 0, model.Adults);
            ObjParam[13] = new DbParameter("@WaitingPeriod", DbParameter.DbType.Int, 0, model.WaitingPeriod);
            ObjParam[14] = new DbParameter("@PolicyLaps", DbParameter.DbType.Int, 0, model.PolicyLaps);
            ObjParam[15] = new DbParameter("@UnderwriterSplit", DbParameter.DbType.Decimal, 0, model.UnderwriterSplit);
            ObjParam[16] = new DbParameter("@AgentSplit", DbParameter.DbType.Decimal, 0, model.AgentSplit);
            ObjParam[17] = new DbParameter("@OfficeSplit", DbParameter.DbType.Decimal, 0, model.OfficeSplit);
            ObjParam[18] = new DbParameter("@CompanySplit", DbParameter.DbType.Decimal, 0, model.CompanySplit);
            ObjParam[19] = new DbParameter("@HeadManagerSplit", DbParameter.DbType.Decimal, 0, model.HeadManagerSplit);
            ObjParam[20] = new DbParameter("@AdminSplit", DbParameter.DbType.Decimal, 0, model.AdminSplit);
            ObjParam[21] = new DbParameter("@LastModified", DbParameter.DbType.DateTime, 0, model.LastModified);
            ObjParam[22] = new DbParameter("@parlourid", DbParameter.DbType.UniqueIdentifier, 0, model.parlourid);
            ObjParam[23] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, model.ModifiedUser);
            ObjParam[24] = new DbParameter("@AdultCover", DbParameter.DbType.Decimal, 0, model.AdultCover);
            ObjParam[25] = new DbParameter("@SpouseCover", DbParameter.DbType.Decimal, 0, model.SpouseCover);
            ObjParam[26] = new DbParameter("@ChildCover", DbParameter.DbType.Decimal, 0, model.ChildCover);
            ObjParam[27] = new DbParameter("@Cover22to40year", DbParameter.DbType.Decimal, 0, model.Cover22to40year);
            ObjParam[28] = new DbParameter("@Cover41to59year", DbParameter.DbType.Decimal, 0, model.Cover41to59year);
            ObjParam[29] = new DbParameter("@Cover60to65year", DbParameter.DbType.Decimal, 0, model.Cover60to65year);
            ObjParam[30] = new DbParameter("@Cover66to75year", DbParameter.DbType.Decimal, 0, model.Cover66to75year);

            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, query, ObjParam));

        }
        public static int DeletePlan(int id)
        {
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@pkiPlanID", DbParameter.DbType.Int, 0, id);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, "DeletePlan", ObjParam));
        }

        public static SqlDataReader GetAllMemberCellphon(Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[1];

            ObjParam[0] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "SendsmsAllMembers", ObjParam);
        }

        public static SqlDataReader GetTemplateList(Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[1];

            ObjParam[0] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetTemplateList", ObjParam);
        }
        public static SqlDataReader GetEmailTemplateByID(int ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetEmailTemplateByID", ObjParam);
        }
        public static int UpdatesmsTemplate(smsTempletModel model)
        {
            smsTempletModel model1 = new smsTempletModel();
            string query = "UpdatesmsTemplate";
            DbParameter[] ObjParam = new DbParameter[6];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, model.ID);
            ObjParam[1] = new DbParameter("@Name", DbParameter.DbType.NVarChar, 0, model.Name);
            ObjParam[2] = new DbParameter("@smsText", DbParameter.DbType.NVarChar, 0, model.smsText);
            ObjParam[3] = new DbParameter("@LastModified", DbParameter.DbType.DateTime, 0, model.LastModified);
            ObjParam[4] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, model.ModifiedUser);
            ObjParam[5] = new DbParameter("@IsActive", DbParameter.DbType.Bit, 0, model.IsActive);

            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, query, ObjParam));

        }
        public static int  SaveTermsAndCondition(ApplicationTnCModel Model1)
        {
            string query = "SaveTermsAndCondition";
            DbParameter[] ObjParam = new DbParameter[9];
            ObjParam[0] = new DbParameter("@pkiAppTC", DbParameter.DbType.Int, 0, Model1.pkiAppTC);
            ObjParam[1] = new DbParameter("@fkiApplicationID", DbParameter.DbType.Int, 0, Model1.fkiApplicationID);
            ObjParam[2] = new DbParameter("@TermsAndCondition", DbParameter.DbType.NVarChar, 0, Model1.TermsAndCondition);
            ObjParam[3] = new DbParameter("@LastModified", DbParameter.DbType.DateTime, 0, Model1.LastModified);
            ObjParam[4] = new DbParameter("@ModifiedUser", DbParameter.DbType.NVarChar, 0, Model1.ModifiedUser);
            ObjParam[5] = new DbParameter("@parlourid", DbParameter.DbType.UniqueIdentifier, 0, Model1.parlourid);
            ObjParam[6] = new DbParameter("@TermsAndConditionFuneral", DbParameter.DbType.NVarChar, 0, Model1.TermsAndConditionFuneral);
            ObjParam[7] = new DbParameter("@TermsAndConditionTombstone", DbParameter.DbType.NVarChar, 0, Model1.TermsAndConditionTombstone);
            ObjParam[8] = new DbParameter("@Declaration", DbParameter.DbType.NVarChar, 0, Model1.Declaration);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, query, ObjParam));
        }

        public static SqlDataReader SelectApplicationTermsAndCondition(Guid parlourid)
        {
            string SP = "SelectApplicationTnCByParlourId";
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, parlourid);

            return DbConnection.GetDataReader(CommandType.StoredProcedure, SP, ObjParam);
        }
        public static int UpdateAutoPolicyNo(ApplicationSettingsModel Model1)
        {
            string query = "update ApplicationSettings set IsAutoGeneratedPolicyNo=@IsAutoGeneratedPolicyNo where parlourid=@parlourid";
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@IsAutoGeneratedPolicyNo", DbParameter.DbType.Bit, 0, Model1.IsAutoGeneratedPolicyNo);
            ObjParam[1] = new DbParameter("@parlourid", DbParameter.DbType.UniqueIdentifier, 0, Model1.parlourid);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.Text, query, ObjParam));
        }
        public static SqlDataReader SelectFuneralManageServiceByParlID(Guid ParlourId, int PageSize, int PageNum, string Keyword, string SortBy, string SortOrder)
        {
            string query = "SelectFuneralManageServiceByParlID";
            DbParameter[] ObjParam = new DbParameter[6];
            ObjParam[0] = new DbParameter("@pagesize", DbParameter.DbType.Int, 0, PageSize);
            ObjParam[1] = new DbParameter("@pagenum", DbParameter.DbType.Int, 0, PageNum);
            ObjParam[2] = new DbParameter("@Keyword", DbParameter.DbType.NVarChar, 0, Keyword);
            ObjParam[3] = new DbParameter("@field", DbParameter.DbType.NVarChar, 0, SortBy);
            ObjParam[4] = new DbParameter("@orderby", DbParameter.DbType.NVarChar, 0, SortOrder);
            ObjParam[5] = new DbParameter("@parlourid", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return (DbConnection.GetDataReader(CommandType.StoredProcedure, query, ObjParam));
        }
        public static int SaveFuneralManageService(FuneralServiceManageModel Model1)
        {
            string query = "SaveFuneralManageService";
            DbParameter[] ObjParam = new DbParameter[7];
            ObjParam[0] = new DbParameter("@pkiServiceID", DbParameter.DbType.Int, 0, Model1.pkiServiceID);
            ObjParam[1] = new DbParameter("@ServiceName", DbParameter.DbType.NVarChar, 0, Model1.ServiceName);
            ObjParam[2] = new DbParameter("@ServiceDesc", DbParameter.DbType.NVarChar, 0, Model1.ServiceDesc);
            ObjParam[3] = new DbParameter("@ServiceCost", DbParameter.DbType.Money, 0, Model1.ServiceCost);
            ObjParam[4] = new DbParameter("@QTY", DbParameter.DbType.Int, 0, Model1.QTY);
            ObjParam[5] = new DbParameter("@parlourid", DbParameter.DbType.UniqueIdentifier, 0, Model1.parlourid);
            ObjParam[6] = new DbParameter("@ModifiedUser", DbParameter.DbType.VarChar, 0, Model1.ModifiedUser);
           
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.StoredProcedure, query, ObjParam));
        }
        public static SqlDataReader SelectFuneralManageServiceByParlANdID(int pkiServiceID, Guid ParlourId)
        {
            string SpName = "SelectFuneralManageServiceByParlANdID";
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@pkiServiceID", DbParameter.DbType.Int, 0, pkiServiceID);
            ObjParam[1] = new DbParameter("@parlourid", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure,SpName, ObjParam);
        }
        public static int DeleteFuneralManageServiceById(int pkiServiceID)
        {
            string query = "Delete from FuneralServices Where pkiServiceID=@pkiServiceID";
            DbParameter[] ObjParam = new DbParameter[1];
            ObjParam[0] = new DbParameter("@pkiServiceID", DbParameter.DbType.Int, 0, pkiServiceID);
            return Convert.ToInt32(DbConnection.GetScalarValue(CommandType.Text, query, ObjParam));

        }
        public static SqlDataReader GetAllApplicationList(Guid parlourid, int param, int AppID)
        {
            string SP = "SelectApplicationList";
            DbParameter[] ObjParam = new DbParameter[3];
            ObjParam[0] = new DbParameter("@parlourid", DbParameter.DbType.UniqueIdentifier, 0, parlourid);
            ObjParam[1] = new DbParameter("@param", DbParameter.DbType.Int, 0, param);
            ObjParam[2] = new DbParameter("@AppID", DbParameter.DbType.Int, 0, AppID);

            return DbConnection.GetDataReader(CommandType.StoredProcedure, SP,ObjParam);
        }
        public static SqlDataReader GetSuperUserAccessByID(int ID, Guid ParlourId)
        {
            DbParameter[] ObjParam = new DbParameter[2];
            ObjParam[0] = new DbParameter("@ID", DbParameter.DbType.Int, 0, ID);
            ObjParam[1] = new DbParameter("@ParlourId", DbParameter.DbType.UniqueIdentifier, 0, ParlourId);
            return DbConnection.GetDataReader(CommandType.StoredProcedure, "GetSuperUserAccessByID", ObjParam);
        }
        
    }
}
